version: '3'

services:
  trade-db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=trade-db
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  trade:
    image: trade
    depends_on:
      - trade-db
    ports:
      - 8080:8080
    environment:
          - DATABASE_HOST=trade-db
          - DATABASE_USER=root
          - DATABASE_PASSWORD=
          - DATABASE_NAME=trade-db
          - DATABASE_PORT=3306